In [1]:
import numpy as np
n1=np.arange(1,20,2)

In [4]:
n2=np.arange(15).reshape(3,5)

In [6]:
n3=np.linspace(1,20,10).reshape(2,5)

In [7]:
n3

array([[ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444],
       [11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ]])

In [15]:
a=np.arange(3)
b=np.arange(3)
d=dict(zip(a,b))
d

{0: 0, 1: 1, 2: 2}

In [22]:
a=np.arange(10).reshape((2,5))
n3+=a

In [28]:
n2


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [33]:
n2[:2].

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [34]:
list(n2.flat)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [44]:
np.full((2,3),10)


array([[10, 10, 10],
       [10, 10, 10]])

In [40]:
n2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 10,  8,  9],
       [10, 11, 12, 13, 14]])

In [45]:
n2.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6, 99,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [48]:
n2.resize((3,5))

In [49]:
n2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 99,  8,  9],
       [10, 11, 12, 13, 14]])

In [55]:
n3.astype(int)

array([[ 1,  4,  7, 10, 13],
       [16, 19, 22, 25, 29]])

In [1]:
import pandas as pd
import openpyxl 

In [2]:
olt=pd.read_excel('OLTDEVICE-2020-03-09-1583718616233.xlsx')
OLT

ImportError: Missing optional dependency 'xlrd'. Install xlrd >= 1.0.0 for Excel support Use pip or conda to install xlrd.