In [1]:
import math

combination = []

def factorization(num, from_num):
	global combination
	if num==from_num:
		combination.append(str(num))
		output()
		combination.pop()
	elif num == 1:
		output()
	else:
		sqrt_n = int(math.sqrt(num))
		if from_num>2:
			start_num = from_num
		else:
			start_num = 2
		for i in range(start_num, sqrt_n+1):
			if num%i==0:
				combination.append(str(i))
				factorization(int(num/i), i)
				combination.pop()
		combination.append(str(num))
		output()
		combination.pop()

def output():
	s = '{}='.format(n)
	s += '*'.join(combination)
	print(s)


n = int(input())
factorization(n, 1)

12
12=2*2*3
12=2*6
12=3*4
12=12


In [9]:
def pandigital(nums):
    alist=[]
    digit='123456789'
    for i in nums:
        si=str(i)
        l=len(si)
        if sorted(list(si))==list(digit[:l]):
            alist.append(i)
    return alist
 
if __name__ == "__main__":
    lst = pandigital(eval(input()))
    if lst:
        for i in lst:
            print(i)
    else:
        print('not found')
    

1243,322,321,1212,2354
1243
321


In [5]:
def countchar(string):
    alp='ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    s=string.upper()
    alist=[s.count(c) for c in alp]
    return alist
if __name__ == "__main__":
    string = input()
    print(countchar(string))

Hello, World!
[0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 3, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0]


In [7]:
str(range(3))

'range(0, 3)'

In [11]:
import numpy as np
a=np.array([[1,2,3],[2,4,5]])
b=np.ones((2,2))
c=np.eye(5)
d=np.zeros((3,3))

In [12]:
a


array([[1, 2, 3],
       [2, 4, 5]])

In [13]:
b

array([[1., 1.],
       [1., 1.]])

In [14]:
c

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
d

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
e=np.full((3,3),10)

In [17]:
e

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [18]:
print(e)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [19]:
print(e.shape)

(3, 3)


In [20]:
f=np.empty((2,3,2))

In [21]:
f

array([[[1.31880229e-311, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.69119330e-306, 7.25085572e-042]],

       [[2.90191894e-057, 8.23570177e-071],
        [2.83305709e-032, 1.25823369e-075],
        [2.48919690e+180, 9.84758306e-072]]])

有5名某界大佬xiaoyun、xiaohong、xiaoteng、xiaoyi和xiaoyang，其QQ号分别是88888、5555555、11111、12341234和1212121，用字典将这些数据组织起来。编程实现以下功能：用户输入某一个大佬的姓名后输出其QQ号，如果输入的姓名不在字典中则输出字符串“Not Found”。

In [25]:
def find_person(dict_users, strU):
     if strU in dict_users:
        return dict_users[strU]
     else:
        return 'Not Found'
if __name__ == "__main__":
     dict_users={'xiaoyun':88888,'xiaohong':5555555,'xiaoteng':11111,'xiaoyi':12341234,'xiaoyang':1212121}
     strU =  input()
     print(find_person(dict_users, strU))

xiaoyun
88888


In [22]:
dict_users={'xiaoyun':88888,'xiaohong':5555555,'xiaoteng':11111,'xiaoyi':12341234,'xiaoyang':1212121}


In [23]:
dict_users['xiaoyun']

88888

In [8]:
def countfeq(s):
    s=s.replace(',',' ')
    s=s.replace('.',' ')
    slist=s.split()
    s_dict=dict()
    for i in slist:
        s_dict[i]=s_dict.get(i,0)+1      
    return s_dict
    
if __name__ == "__main__":
    s = "Not clumsy person in this world, only lazy people, only people can not hold out until the last."
    s_dict = countfeq(s.lower())
    word = input()
    try:
        print(s_dict[word.lower()])
    except:
        print(0)


not
2


In [7]:
ali=[1,2,2,3]
ali.count(2)

2

In [1]:
import pandas as pd
import numpy as np
np.random.randint()
s='abc'
s.count()


TypeError: randint() takes at least 1 positional argument (0 given)

In [2]:
%lsmagic


Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %colors  %conda  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %matplotlib  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python 

In [27]:
%%cmd
regedit


Microsoft Windows [版本 10.0.18363.693]
(c) 2019 Microsoft Corporation。保留所有权利。

C:\Users\dglin>regedit

C:\Users\dglin>

In [1]:
import numpy as np
np.__version__

'1.18.1'

In [2]:
x=np.arange(0,1000)

In [5]:
%timeit x.sum()

2.8 µs ± 36.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [6]:
sum(x)

499500

In [7]:
%timeit sum(x)

156 µs ± 2.46 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [49]:
t=np.random.randn(5,5)
a=np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)]
print(a.shape)
t.mean()

SyntaxError: invalid syntax (<ipython-input-49-c9b40e7cc44f>, line 3)

In [14]:
np.linspace(1,100,num=10,axis=0)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [29]:
n1=np.random.normal(loc=200,scale=10,size=10000)

In [30]:
n1.mean()

199.8777122090882

In [33]:
with open('t.txt', 'r+') as fp:
    fp.seek(15)
    print(fp.readline())

you need Python.



In [34]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
numbers[0::3]

[1, 4, 7, 10]

In [35]:
my_list = [s.lower() for s in 'Life is short, you need Python.'.split(' ')]
print('short' in my_list)
print(my_list[5])


False
python.


In [36]:
print(list('Life is short, you need Python.').count('is'))

0


In [37]:
language = list('PHP')
language[1:] = 'ython'
print(language)

['P', 'y', 't', 'h', 'o', 'n']


In [39]:
print('you' in 'Life is short, you need Python.')

True


In [41]:
print('{:2d},{:8s}:{:3d}'.format(1,'abcdef', 6))

 1,abcdef  :  6


In [42]:
(1, 2)  in zip(range(4), range(2,6))

False

In [43]:
dict_mark_1 = {'Wang': 98, 'Li': 87, 'Ma': 93}
dict_mark_2 = {'Li': 90, 'Ma': 95, 'Xu': 75}
dict_mark_1.update(dict_mark_2)
dict_mark_1.pop('Li')

90

In [44]:
sorted(set('You need Python.'))[2]


'P'

In [45]:
set('You need Python.')

{' ', '.', 'P', 'Y', 'd', 'e', 'h', 'n', 'o', 't', 'u', 'y'}

In [47]:
a=np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)]
a.shape()          

SyntaxError: invalid syntax (<ipython-input-47-63b51a062387>, line 2)

In [50]:
from pandas import Series
sa = Series(['a', 'b', 'c'], index = [0, 1, 2])
sb = Series(['a', 'b', 'c'])
sc = Series(['a', 'c', 'b'])
sa*3 + sc*2

0    aaaaa
1    bbbcc
2    cccbb
dtype: object

In [51]:
sa*3

0    aaa
1    bbb
2    ccc
dtype: object

In [53]:
import numpy as np
n2=np.random.randint(0,100,size=(5,3))

In [62]:
n2[1:3,1:]


array([[21, 78],
       [87, 71]])

In [63]:
l2=[[22, 64,  9],
       [ 1, 21, 78],
       [99, 87, 71],
       [22, 46, 54],
       [69, 89, 49]]

In [68]:
l2[2][1]

87